language: go

# This takes a little bit of pressure off of the git clone of this repo.
git:
  depth: 3

# Let's skip the install process for now. We don't need to install anything.
install: true

script:
  - go test github.com/ankeesler/anwork_testing/core
  - go test github.com/ankeesler/anwork_testing/v1

notifications:
  email:
    recipients:
      - ankeesler1@gmail.com
    on_success: changed
    on_failure: always
